{% set version = "1.1.2" %}

package:
  name: pydoe2
  version: {{ version }}

source:
    fn: pyDOE2-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pydoe2/pyDOE2-{{ version }}.tar.gz
    sha256: 1d6fefd4e4ac1882436994d2dd91777fe829cd8cf08c92e5f7533f494b26699f

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - scipy >=0.13
    - numpy >=1.8

test:
  imports:
    - pyDOE2

about:
  home: https://github.com/clicumu/pyDOE2
  license_family: BSD
  license: BSD 3-Clause
  # https://github.com/clicumu/pyDOE2/pull/7
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Design of experiments for Python
  description: Fork of pyDOE, package designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.

extra:
  recipe-maintainers:
    - jschueller
    - druvus
