travis:
  secure:
    BINSTAR_TOKEN: x8hVf3sl3HMD+MexNowUKFkn5gOis3npcp/fASkIi4/vQRLOjU5VpMtqNEdaAvhPXDfR4B2VyO3THeAmfbKEQC/pSsfveAvbG1TuTA+TDXReKOu5u8uMdPjl/blB2TaFEN65HkPOzJbuWrmZ9C4GYTN0hjyoBASZeUk+fS5tdt9z0BnoZYd1kki2P9unKxUjsNb4YRiWCfOwjbeHwZJ+VsLmQ0ruhWEXEj9lRBhwxcVJ0kIn9V5wgDxWeTPkOXWX8SzsursKrMn/H/BCfcUig4fCxOySBeuwvUvwybcBSzysw+NCZtYUNFPfDyCP7Nou5VueQNzDOIfFNlRAhqJr39/E3cz1YdPA7VQ7RV3+Cy8oad/OzrXNuKjro0zAiJacf2zCFO0ybLHa40K2KkTRQ+x5J1AywDmr05dOtxlEvsibS3FymASx6hNRp0QBR2ylhdPCCLm+mnfBgA9lRgmesTgXMeHt+lzDZ/rNSAGPNPM/H7gGlKr0sU4K7oH/4Go7Ud0KC5AsyawSZBKV2dgMw0oXtiQWCoPRBOlWCofxvmaTQvzHVhgmdGHNC4GxIWQVo0nDunXaxlN+lBAHEq1clSVv6TLwPLyt7fT66JBhlPmxFX1TQsbiWcntzDrD7PgzEsARjrffyGLoDuMMp2cFa2pqwhiLE+XCmfdDmynoOBI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
